### ISSUE TITLE
Crash when taking screenshot

### ISSUE THREAD

**Issue by helpimnotdrowning** [UltimateBoomer/Resolution-Control#5]
Game crashes when taking a screenshot with the Screenshot Framebuffer keybind.
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/26/21, 9:44 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_318.method_22690(java.io.File, java.lang.String, int, int, net.minecraft.class_276, java.util.function.Consumer)'
	at io.github.ultimateboomer.resolutioncontrol.ResolutionControlMod.saveScreenshot(ResolutionControlMod.java:130)
	at io.github.ultimateboomer.resolutioncontrol.ResolutionControlMod.setShouldScale(ResolutionControlMod.java:185)
	at net.minecraft.class_757.handler$zkc000$onRenderWorldEnd(class_757.java:2005)
	at net.minecraft.class_757.method_3188(class_757.java:1055)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.ultimateboomer.resolutioncontrol.ResolutionControlMod.saveScreenshot(ResolutionControlMod.java:130)
	at io.github.ultimateboomer.resolutioncontrol.ResolutionControlMod.setShouldScale(ResolutionControlMod.java:185)
	at net.minecraft.class_757.handler$zkc000$onRenderWorldEnd(class_757.java:2005)
	at net.minecraft.class_757.method_3188(class_757.java:1055)

-- Affected level --
Details:
	All players: 1 total; [class_746['iamdrowning'/151, l='ClientLevel', x=49.16, y=64.00, z=0.72]]
	Chunk stats: 16384, 3969
	Level dimension: minecraft:overworld
	Level spawn location: World: (39,63,14), Section: (at 7,15,14 in 2,3,0; chunk contains blocks 32,0,0 to 47,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 19493 game time, 500 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Classic Alternative, MCPE Stonecutter, Slimecicle, Vanilla Tweaks, Vistas Panoramas

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 3095312408 bytes (2951 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 2112.00
	Graphics card #0 deviceId: 0x0152
	Graphics card #0 versionInfo: DriverVersion=10.18.10.4358
	Graphics card #1 name: NVIDIA GeForce GT 1030
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1d01
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6079
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 47643.13
	Virtual memory used (MB): 26629.84
	Swap memory total (MB): 27288.18
	Swap memory used (MB): 1849.99
	JVM Flags: 20 total; -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
	Fabric Mods: 
		adventure-platform-fabric: adventure-platform-fabric 4.1.0-SNAPSHOT
		antighost: AntiGhost 1.17-fabric0.34.9-1.1.4
		architectury: Architectury 2.1.20
		audiooutput: AudioOutput 0.0.4
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betterbeds: Better Beds 1.2.0
		bettereating: Better Eating 0.3.0
		capes: Capes 1.2.0
		carpet: Carpet Mod 1.4.42
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		cloud-v1: Cloud 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-brigadier: cloud-brigadier 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-core: cloud-core 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-services: cloud-services 1.5.0-SNAPSHOT
		colormatic: Colormatic 2.2.9-snapshot+mc.1.17
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		commandaliases: Command Aliases 0.4.2
		cr3stal: Cr³stal 1.0.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		custom-fog: Custom Fog 1.6.0
		customstars: Custom Stars 0.5
		damagetilt: Damage Tilt 1.17-fabric-0.1.2
		dcch: DCCH 1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dynamicfps: Dynamic FPS 2.0.4
		entityculling: EntityCulling-Fabric 1.3.2
		extrasounds: Extra Sounds 1.4.1
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446313
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.2+1.17
		ferritecore: FerriteCore 3.0.1
		fiber: fiber 0.23.0-2
		fullscreeno: fullscreeNO 1.0.0
		hydrogen: Hydrogen 0.3-SNAPSHOT
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		inventoryprofilesnext: Inventory Profiles Next 0.8.1
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.0-starline+build.418
		isometric-renders: Isometric Renders 0.2.5
		itemmodelfix: Item Model Fix 1.0.2+1.17
		java: OpenJDK 64-Bit Server VM 16
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		legacy_display: Legacy Display 1.1.3
		libzoomer: LibZoomer 0.2.1+1.17
		lightoverlay: Light Overlay 6.0.0
		litematica: Litematica 0.0.0-dev.20210616.033538
		lithium: Lithium 0.7.3
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17.1
		modern_beta: Modern Beta Fabric 2.1.1-1.17.1
		modmenu: Mod Menu 2.0.2
		net_kyori_adventure-api: adventure-api 4.8.1
		net_kyori_adventure-key: adventure-key 4.8.1
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.8.0
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.8.1
		net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.8.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.8.1
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		pickblockstate: Pick-BlockState 1.0.0+1.17
		plasmo_voice: Plasmo Voice 1.0.7
		pling: Pling 1.3.0
		resolutioncontrol: ResolutionControl+ 3.0.0
		roughlyenoughitems: Roughly Enough Items 6.0.262-alpha
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.0+IRIS1-build.105
		soundphysics: Sound Physics 2.0.0
		spruceui: SpruceUI 3.2.0+1.17
		stairdoors-fabric: StairDoors Fabric 2.3.1
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		swordblocking: Sword Blocking 1.1.0
		tabtps-fabric: TabTPS 1.3.8
		vistas: Vistas 1.3.3
		worldedit: WorldEdit 7.3.0-SNAPSHOT+10410ac
		worldmesher: Worldmesher 0.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 460.79, NVIDIA Corporation
	Window size: 2160x1620
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Classic Alternative (incompatible), file/MCPE Stonecutter, file/Slimecicle, file/Vanilla Tweaks, file/Vistas Panoramas
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	Player Count: 1 / 8; [class_3222['iamdrowning'/151, l='ServerLevel[pack.png]', x=49.16, y=64.00, z=0.72]]
	Data Packs: vanilla (incompatible), Fabric Mods
```

**Comment by helpimnotdrowning** [comment]
This also happens with just ResolutionControl+ and Fabric API.

**Comment by JonathanTippy** [comment]
i also have this issue.

**Comment by JonathanTippy** [comment]
if this issue could be fixed, i wouldn't mind the incompatibility with fabrishot.

**Comment by frugbug** [comment]
I also have this issue with an R9 Fury GPU, using just FAPI and this mod.

**Comment by JonathanTippy** [comment]
btw i have an i5 4440 and gtx 1060. could this be a problem with older cpus?
